import type { ListingCardData } from "@/components/marketplace/ListingCard";

/**
 * Frontend-only demo data for Phase 1 layout work. Not wired to Supabase,
 * not written anywhere, not a data-layer design — purely for demonstrating
 * the ListingCard/ListingRail system before real queries exist.
 */

export const MOCK_FRESH_FINDS: ListingCardData[] = [
  {
    id: "mock-1",
    title: "Uniqlo Airism Crew Neck Shirt, Size M",
    priceCents: 45000,
    listingType: "preloved",
    condition: "very_good",
    locationLabel: "Tangub City",
    postedLabel: "2 hours ago",
    shopName: "Anne's Closet",
  },
  {
    id: "mock-2",
    title: "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
    priceCents: 890000,
    originalPriceCents: 1200000,
    listingType: "preloved",
    condition: "like_new",
    locationLabel: "Ozamiz City",
    postedLabel: "4 hours ago",
    shopName: "Techville PH",
  },
  {
    id: "mock-3",
    title: "Brand New Baby Onesie Bundle (0–3 months, 5 pcs)",
    priceCents: 65000,
    listingType: "brand_new",
    locationLabel: "Tangub City",
    postedLabel: "5 hours ago",
    shopName: "Little Sprout Shop",
  },
  {
    id: "mock-4",
    title: "Nike Air Max 270, Size 9",
    priceCents: 320000,
    isNegotiable: true,
    listingType: "preloved",
    condition: "good",
    locationLabel: "Dipolog City",
    postedLabel: "6 hours ago",
    shopName: "Sole Traders",
  },
  {
    id: "mock-5",
    title: "Rattan Accent Chair",
    priceCents: 250000,
    originalPriceCents: 380000,
    listingType: "preloved",
    condition: "fair",
    locationLabel: "Misamis Occidental",
    postedLabel: "8 hours ago",
    shopName: "Home & Haven",
  },
  {
    id: "mock-6",
    title: "Brand New Stainless Steel Water Bottle, 1L",
    priceCents: 0,
    listingType: "brand_new",
    locationLabel: "Tangub City",
    postedLabel: "9 hours ago",
    shopName: "EcoCarry PH",
  },
  {
    id: "mock-7",
    title: "Canon EOS M50 Mirrorless Camera with 15-45mm Lens",
    priceCents: 1850000,
    isNegotiable: true,
    listingType: "preloved",
    condition: "very_good",
    locationLabel: "Cagayan de Oro",
    postedLabel: "1 day ago",
    shopName: "Shutter Finds",
  },
  {
    id: "mock-8",
    title: "Brand New Ceramic Cookware Set (5-piece)",
    priceCents: 275000,
    originalPriceCents: 340000,
    listingType: "brand_new",
    locationLabel: "Tangub City",
    postedLabel: "1 day ago",
    shopName: "Kusina Essentials",
  },
];

export const MOCK_PRE_LOVED: ListingCardData[] = [
  {
    id: "mock-preloved-1",
    title: "Zara Trench Coat, Size S",
    priceCents: 180000,
    listingType: "preloved",
    condition: "good",
    locationLabel: "Tangub City",
    postedLabel: "3 hours ago",
    shopName: "Anne's Closet",
  },
  {
    id: "mock-preloved-2",
    title: "Herschel Backpack",
    priceCents: 95000,
    isNegotiable: true,
    listingType: "preloved",
    condition: "very_good",
    locationLabel: "Ozamiz City",
    postedLabel: "1 day ago",
    shopName: "Wanderpack",
  },
  {
    id: "mock-preloved-3",
    title: "Vintage Polaroid Camera (working)",
    priceCents: 220000,
    listingType: "preloved",
    condition: "fair",
    locationLabel: "Dipolog City",
    postedLabel: "2 days ago",
    shopName: "Retro Finds Co.",
  },
  {
    id: "mock-preloved-4",
    title: "IKEA Poang Chair",
    priceCents: 150000,
    originalPriceCents: 210000,
    listingType: "preloved",
    condition: "like_new",
    locationLabel: "Tangub City",
    postedLabel: "2 days ago",
    shopName: "Home & Haven",
    status: "reserved",
  },
];

export const MOCK_BRAND_NEW: ListingCardData[] = [
  {
    id: "mock-brandnew-1",
    title: "Brand New Non-Stick Frying Pan, 28cm",
    priceCents: 89000,
    listingType: "brand_new",
    locationLabel: "Tangub City",
    postedLabel: "5 hours ago",
    shopName: "Kusina Essentials",
  },
  {
    id: "mock-brandnew-2",
    title: "Brand New Wireless Earbuds",
    priceCents: 145000,
    originalPriceCents: 190000,
    listingType: "brand_new",
    locationLabel: "Ozamiz City",
    postedLabel: "7 hours ago",
    shopName: "Techville PH",
  },
  {
    id: "mock-brandnew-3",
    title: "Brand New Yoga Mat with Carry Strap",
    priceCents: 55000,
    isNegotiable: true,
    listingType: "brand_new",
    locationLabel: "Tangub City",
    postedLabel: "1 day ago",
    shopName: "Sunrise Wellness",
  },
  {
    id: "mock-brandnew-4",
    title: "Brand New Kids' Building Blocks Set",
    priceCents: 72000,
    listingType: "brand_new",
    locationLabel: "Cagayan de Oro",
    postedLabel: "1 day ago",
    shopName: "Little Sprout Shop",
  },
];
