-- Location reference tables for the approved Preshopps schema design.
-- Structural schema only: identity/profile tables, shops, listings, carts,
-- orders, messaging, reviews, moderation, RLS, storage, and RPCs are all
-- created in later migrations (see the approved migration strategy).
--
-- Foreign keys use ON DELETE RESTRICT: these are effectively immutable
-- reference tables, and a parent location row must never be silently
-- removable while child rows (or, later, any application data) still
-- reference it.
--
-- No indexes are added beyond the primary keys and unique constraints
-- below. Each unique constraint's leading column is exactly the foreign
-- key used to look up children by parent (e.g. the unique constraint on
-- provinces(country_code, name) already serves "all provinces in this
-- country" lookups, not just the uniqueness check), so a separate
-- single-column index on the foreign key would be redundant.

create table countries (
  code char(2) primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table provinces (
  id integer generated by default as identity primary key,
  country_code char(2) not null references countries (code) on delete restrict,
  name text not null,
  created_at timestamptz not null default now(),
  unique (country_code, name)
);

create table cities_municipalities (
  id integer generated by default as identity primary key,
  province_id integer not null references provinces (id) on delete restrict,
  name text not null,
  created_at timestamptz not null default now(),
  unique (province_id, name)
);

create table barangays (
  id integer generated by default as identity primary key,
  city_id integer not null references cities_municipalities (id) on delete restrict,
  name text not null,
  created_at timestamptz not null default now(),
  unique (city_id, name)
);

insert into countries (code, name)
values ('PH', 'Philippines')
on conflict (code) do nothing;
