-- Categories reference table for the approved Preshopps schema design.
-- Structural schema only: shops, listings, location-hierarchy changes,
-- carts, orders, messaging, reviews, notifications, moderation, disputes,
-- support, storage buckets, RPCs, and application RLS policies are all
-- created in later migrations (see the approved migration strategy).
--
-- is_inquiry_only encodes PRD's Cars/Motorcycles/For Rent rule as data,
-- not a hardcoded category-name check scattered through the app — the
-- single source of truth for hiding Add to Cart for those categories.
--
-- No updated_at: categories are admin-managed reference data, matching
-- the approved schema's treatment of this table.
--
-- No indexes beyond the PK and the two UNIQUE constraints below. This
-- table will only ever hold a small, fixed number of rows (13 today),
-- and the one real query — "list all categories in display order" — is
-- a full scan regardless of any index at that size; a dedicated index
-- on sort_order or is_inquiry_only would be speculative.

create table categories (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null,
  is_inquiry_only boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (name),
  unique (slug),
  check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

-- Approved initial category set. sort_order uses 10-step increments
-- (10, 20, 30, ...) so future categories can be inserted between
-- existing ones without renumbering the whole table.
--
-- Plain INSERT, no ON CONFLICT: this table was just created above, so
-- there is no legitimate pre-existing data to conflict with — a unique
-- violation here would mean something unexpected, and the migration
-- should fail loudly rather than silently mask it.
insert into categories (name, slug, is_inquiry_only, sort_order) values
  ('Women', 'women', false, 10),
  ('Men', 'men', false, 20),
  ('Kids & Baby', 'kids-baby', false, 30),
  ('Shoes', 'shoes', false, 40),
  ('Bags & Accessories', 'bags-accessories', false, 50),
  ('Electronics', 'electronics', false, 60),
  ('Home & Living', 'home-living', false, 70),
  ('Beauty & Personal Care', 'beauty-personal-care', false, 80),
  ('Sports & Hobbies', 'sports-hobbies', false, 90),
  ('Cars', 'cars', true, 100),
  ('Motorcycles', 'motorcycles', true, 110),
  ('For Rent', 'for-rent', true, 120),
  ('Other', 'other', false, 130);
