-- Category taxonomy reconciliation: the live public.categories table has
-- carried three additional categories (Foods, Bicycle, Pet) since
-- 2026-09-04, added directly against the live database outside any
-- tracked migration -- a real, reported drift between the schema-as-
-- migrated and the schema-as-deployed. This migration is purely additive
-- and idempotent: it brings a fresh environment (only 0005's original 13
-- rows) up to the same 16-category state the live database already has,
-- and is a safe no-op when run again against the current live database.
-- No existing row's id, name, slug, is_inquiry_only, or created_at is
-- ever touched, no row is deleted or recreated, and no table, enum, or
-- RLS policy is created or altered.
--
-- Pre-inspection findings (read-only, immediately before writing this file)
-- -----------------------------------------------------------------------
-- Live public.categories queried directly (all 6 columns: id, name, slug,
-- is_inquiry_only, sort_order, created_at) immediately before writing this
-- file. The original 13 rows from 0005 are unchanged (ids 1-13; the first
-- 12 still sort_order 10-120; Cars/Motorcycles/For Rent still
-- is_inquiry_only = true). Three additional live rows exist, added
-- outside any migration: Foods (id 15, slug 'foods', is_inquiry_only
-- false, sort_order 130, created_at 2026-09-04), Bicycle (id 16, slug
-- 'bicycle', is_inquiry_only false, sort_order 140, created_at
-- 2026-09-04), Pet (id 14, slug 'pet', is_inquiry_only false, sort_order
-- 150, created_at 2026-09-04). Other (id 13) already carries sort_order
-- 160 live -- it was manually bumped up from 0005's original 130 when
-- Foods/Bicycle/Pet were inserted ahead of it, following the exact same
-- 10-step sort_order convention 0005's own header established ("future
-- categories can be inserted between existing ones without renumbering
-- the whole table"). categories.id is `generated by default as identity`
-- (0005) -- this migration never specifies an id for Foods/Bicycle/Pet,
-- matching 0005's own convention, since the live ids (14/15/16) were
-- themselves identity-assigned, not hand-picked, and nothing anywhere in
-- this codebase references a category by a hardcoded id (only by slug or
-- by the category_id FK already stored on listings).
--
-- Idempotency mechanism
-- -----------------------------------------------------------------------
-- categories.slug already carries a UNIQUE constraint (0005) -- the
-- INSERT below uses ON CONFLICT (slug) DO NOTHING, so running this
-- migration against the current live database (where all three slugs
-- already exist) inserts zero rows and touches nothing; running it
-- against a fresh environment (only 0005 applied) inserts exactly the
-- three missing rows once, in the exact same shape as the live rows. The
-- Other sort_order UPDATE is similarly guarded (only fires when the
-- value is not already 160), so it is a no-op on the current live
-- database and a one-time correction on a fresh environment.
--
-- Category behavior otherwise unchanged
-- -----------------------------------------------------------------------
-- Foods/Bicycle/Pet are ordinary sale categories (is_inquiry_only =
-- false), matching every category except Cars/Motorcycles/For Rent. This
-- migration does not touch Cars/Motorcycles/For Rent at all -- their
-- is_inquiry_only = true and sort_order (100/110/120) remain exactly as
-- 0005 left them, so the existing Add-to-Cart-hiding behavior for those
-- three categories is unaffected.

insert into public.categories (name, slug, is_inquiry_only, sort_order) values
  ('Foods', 'foods', false, 130),
  ('Bicycle', 'bicycle', false, 140),
  ('Pet', 'pet', false, 150)
on conflict (slug) do nothing;

update public.categories
  set sort_order = 160
  where slug = 'other'
    and sort_order <> 160;
